### ISSUE TITLE
Barber cannot support library project

### ISSUE THREAD

**Issue by JackCho** [hzsweers/barber#18]
error msg : attribute value must be constant

**Comment by ZacSweers** [comment]
Can you give some more context? I suspect it's because you're passing in a non-constant value to the `value` member of one of the annotations, which isn't possible. I don't understand what you mean by "cannot support library project though"

**Comment by JackCho** [comment]
@StyledAttr(value = R.styleable.superrecyclerview_recyclerClipToPadding)
    protected boolean mClipToPadding = false;
    @StyledAttr(value = R.styleable.superrecyclerview_recyclerPadding, kind = Kind.DIMEN)
    protected int mPadding = -1;

@hzsweers

**Comment by JackCho** [comment]
my custom view is in an library project, and its fields in R file are all not final.
Have any idea? 

I find a link : http://tools.android.com/tips/non-constant-fields

**Comment by ZacSweers** [comment]
Ah. Yes, library project styleable resources are not final. From the [tools site](http://tools.android.com/tips/non-constant-fields):

>  the constants are not final in a library project. The reason for this is simple: When multiple library projects are combined, the actual values of the fields (which must be unique) could collide. Before ADT 14, all fields were final, so as a result, all libraries had to have all their resources and associated Java code recompiled along with the main project whenever they were used. This was bad for performance, since it made builds very slow. It also prevented distributing library projects that didn't include the source code, limiting the usage scope of library projects.
> 
> The reason the fields are no longer final is that it means that the library jars can be compiled once and reused directly in other projects. As well as allowing distributing binary version of library projects (coming in r15), this makes for much faster builds.

There's nothing I can really do about this, it's a limitation of annotations. You'd have the same problem if you used any other annotation processor that used resource values (such as Butterknife with IDs)

I don't think libraries should be including stuff like this anyway. It's extra hassle for the user because then they have to set up the apt/provided dependency and whatnot as well, while inadvertently inheriting another library dependency that they might not really need.

**Comment by Jawnnypoo** [comment]
I don't think the end user would actually have to mess with the apt stuff if you were exporting your library project as a .aar. But yes, I could see how this would be an issue in the same way as ButterKnife is. Its too bad, I would have loved to have this convenience in a library project
